import {mkdir, writeFile} from "fs/promises";
import * as path from "path";
import {execFile} from "child_process";
import {
  fetchTranscript as fetchTranscriptPlus,
} from "@egoist/youtube-transcript-plus";
import {YoutubeTranscript as YoutubeTranscriptApi} from "youtube-transcript";

export type ExportMode = "dry-run" | "scheduled";

export type ExportFilters = {
  titleKeywords?: string[];
};

export type StreamVideo = {
  videoId: string;
  title: string;
  videoUrl: string;
  publishedText: string;
};

export type TranscriptResult = {
  text: string;
  source: string;
  languageCode: string | null;
  isAutoGenerated: boolean | null;
};

export type WatchVideoMetadata = {
  publishedAt: Date | null;
  speaker: string | null;
};

export type TranscriptDocumentMetadata = {
  title: string;
  videoUrl: string;
  sourcePage: string;
  publishedText: string;
  publishedAt: Date | null;
  fetchedAt: Date | null;
  transcriptSource: string;
  languageCode: string | null;
  isAutoGenerated: boolean | null;
  speaker: string | null;
};

export type ParsedTranscriptDocument = {
  metadata: TranscriptDocumentMetadata;
  transcriptText: string;
};

/**
 * Remove non-ASCII characters after Unicode normalization.
 *
 * @param {string} value Input text.
 * @return {string} ASCII-only text.
 */
function stripNonAscii(value: string): string {
  return Array.from(value)
    .filter((char) => char.charCodeAt(0) <= 0x7f)
    .join("");
}

export type SavedTranscriptFile = {
  video: StreamVideo;
  filePath: string;
  transcript: TranscriptResult;
  metadata: WatchVideoMetadata;
};

export type SkippedTranscriptVideo = {
  video: StreamVideo;
  reason: string;
};

export type ExportRunResult = {
  channelUrl: string;
  mode: ExportMode;
  limit: number;
  titleKeywords: string[];
  errorMessage?: string | null;
  saved: SavedTranscriptFile[];
  skipped: SkippedTranscriptVideo[];
};

export type MultiChannelExportResult = {
  mode: ExportMode;
  limit: number;
  titleKeywords: string[];
  results: ExportRunResult[];
};

type TranscriptDocumentOptions = {
  metadata?: WatchVideoMetadata;
};

type CaptionTrack = {
  baseUrl: string;
  languageCode: string;
  isAutoGenerated: boolean;
};

type RawTextFetcher = (url: string) => Promise<string>;

const DEFAULT_HEADERS = {
  "Accept-Language": "en-US,en;q=0.9",
  "User-Agent":
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) " +
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36",
};
const STREAM_DISCOVERY_ATTEMPTS = 3;

/**
 * Sleep for the provided number of milliseconds.
 *
 * @param {number} delayMs Delay in milliseconds.
 * @return {Promise<void>} Resolves after the delay.
 */
function delay(delayMs: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, delayMs));
}

/**
 * Fetch a URL as text with a browser-like user agent.
 *
 * @param {string} url URL to fetch.
 * @return {Promise<string>} Response body text.
 */
async function fetchText(url: string): Promise<string> {
  try {
    return await fetchTextViaCurl(url);
  } catch {
    const response = await fetch(url, {
      method: "GET",
      redirect: "follow",
      headers: DEFAULT_HEADERS,
    });
    if (!response.ok) {
      throw new Error(`HTTP ${response.status} for ${url}`);
    }
    return response.text();
  }
}

/**
 * Fetch a URL as text using curl for better compatibility with YouTube pages.
 *
 * @param {string} url URL to fetch.
 * @return {Promise<string>} Response body text.
 */
function fetchTextViaCurl(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    execFile(
      "curl",
      [
        "-L",
        "--silent",
        "--show-error",
        "--max-time",
        "30",
        "-A",
        DEFAULT_HEADERS["User-Agent"],
        "-H",
        `Accept-Language: ${DEFAULT_HEADERS["Accept-Language"]}`,
        url,
      ],
      {maxBuffer: 10 * 1024 * 1024},
      (error, stdout) => {
        if (error) {
          reject(error);
          return;
        }
        resolve(stdout);
      }
    );
  });
}

/**
 * Return a plain object view when possible.
 *
 * @param {unknown} value Candidate value.
 * @return {Record<string, unknown> | null} Plain record or null.
 */
function asRecord(value: unknown): Record<string, unknown> | null {
  return value && typeof value === "object" && !Array.isArray(value) ?
    value as Record<string, unknown> :
    null;
}

/**
 * Read a nested value from an object path.
 *
 * @param {unknown} value Root value.
 * @param {Array<string | number>} keys Object path.
 * @return {unknown} Nested value.
 */
function getNested(
  value: unknown,
  keys: Array<string | number>
): unknown {
  let current: unknown = value;
  for (const key of keys) {
    if (typeof key === "number") {
      if (!Array.isArray(current) || key >= current.length) {
        return undefined;
      }
      current = current[key];
      continue;
    }

    const record = asRecord(current);
    if (!record || !(key in record)) {
      return undefined;
    }
    current = record[key];
  }
  return current;
}

/**
 * Flatten text content from common YouTube text objects.
 *
 * @param {unknown} value Raw YouTube text payload.
 * @return {string} Flattened text.
 */
function flattenText(value: unknown): string {
  if (typeof value === "string") {
    return value.trim();
  }

  const record = asRecord(value);
  if (!record) {
    return "";
  }

  if (typeof record.content === "string") {
    return record.content.trim();
  }

  const simpleText = record.simpleText;
  if (typeof simpleText === "string") {
    return simpleText.trim();
  }

  const runs = record.runs;
  if (Array.isArray(runs)) {
    return runs
      .map((run) => {
        const runRecord = asRecord(run);
        return runRecord && typeof runRecord.text === "string" ?
          runRecord.text :
          "";
      })
      .join("")
      .trim();
  }

  return "";
}

/**
 * Extract a JSON object that appears after a marker string.
 *
 * @param {string} source Full source text.
 * @param {string} marker Marker preceding the JSON object.
 * @return {unknown | null} Parsed JSON object or null.
 */
function extractJsonObjectAfterMarker(
  source: string,
  marker: string
): unknown | null {
  const markerIndex = source.indexOf(marker);
  if (markerIndex < 0) {
    return null;
  }

  const objectStart = source.indexOf("{", markerIndex + marker.length);
  if (objectStart < 0) {
    return null;
  }

  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let i = objectStart; i < source.length; i++) {
    const char = source[i];
    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === "\"") {
        inString = false;
      }
      continue;
    }

    if (char === "\"") {
      inString = true;
      continue;
    }
    if (char === "{") {
      depth++;
      continue;
    }
    if (char === "}") {
      depth--;
      if (depth === 0) {
        const rawJson = source.slice(objectStart, i + 1);
        try {
          return JSON.parse(rawJson);
        } catch {
          return null;
        }
      }
    }
  }

  return null;
}

/**
 * Parse YouTube initial data from raw channel HTML.
 *
 * @param {string} html Channel page HTML.
 * @return {Record<string, unknown>} Parsed initial data.
 */
function extractInitialDataFromHtml(
  html: string
): Record<string, unknown> {
  const markers = [
    "var ytInitialData = ",
    "window['ytInitialData'] = ",
    "window[\"ytInitialData\"] = ",
    "ytInitialData = ",
  ];
  for (const marker of markers) {
    const parsed = extractJsonObjectAfterMarker(html, marker);
    const record = asRecord(parsed);
    if (record) {
      return record;
    }
  }

  throw new Error("Unable to parse YouTube initial data from channel page.");
}

/**
 * Pick the Streams tab from YouTube initial data when available.
 *
 * @param {Record<string, unknown>} initialData Parsed initial data.
 * @return {Record<string, unknown> | null} Tab renderer payload or null.
 */
function findStreamsTab(
  initialData: Record<string, unknown>
): Record<string, unknown> | null {
  const tabs = getNested(
    initialData,
    ["contents", "twoColumnBrowseResultsRenderer", "tabs"]
  );
  if (!Array.isArray(tabs)) {
    return null;
  }

  for (const tab of tabs) {
    const renderer = asRecord(asRecord(tab)?.tabRenderer);
    if (!renderer) {
      continue;
    }

    const title = flattenText(renderer.title).toLowerCase();
    const endpointUrl = flattenText(
      getNested(
        renderer,
        ["endpoint", "commandMetadata", "webCommandMetadata", "url"]
      )
    ).toLowerCase();
    if (title === "streams" || endpointUrl.endsWith("/streams")) {
      return renderer;
    }
  }

  return null;
}

/**
 * Extract a rich-grid contents array from a tab renderer.
 *
 * @param {Record<string, unknown> | null} tabRenderer Tab renderer payload.
 * @return {unknown[] | null} Grid contents or null.
 */
function extractRichGridContents(
  tabRenderer: Record<string, unknown> | null
): unknown[] | null {
  const contents = getNested(
    tabRenderer,
    ["content", "richGridRenderer", "contents"]
  );
  return Array.isArray(contents) ? contents : null;
}

/**
 * Pick a fallback channel tab that exposes a video grid.
 *
 * Used for channels that do not expose a dedicated Streams tab.
 *
 * @param {Record<string, unknown>} initialData Parsed initial data.
 * @return {Record<string, unknown> | null} Tab renderer payload or null.
 */
function findFallbackChannelTab(
  initialData: Record<string, unknown>
): Record<string, unknown> | null {
  const tabs = getNested(
    initialData,
    ["contents", "twoColumnBrowseResultsRenderer", "tabs"]
  );
  if (!Array.isArray(tabs)) {
    return null;
  }

  for (const tab of tabs) {
    const renderer = asRecord(asRecord(tab)?.tabRenderer);
    if (!renderer) {
      continue;
    }

    const title = flattenText(renderer.title).toLowerCase();
    if (!["home", "videos", "live"].includes(title)) {
      continue;
    }
    if (extractRichGridContents(renderer)) {
      return renderer;
    }
  }

  for (const tab of tabs) {
    const renderer = asRecord(asRecord(tab)?.tabRenderer);
    if (renderer && extractRichGridContents(renderer)) {
      return renderer;
    }
  }

  return null;
}

/**
 * Convert a streams tab item into a normalized stream video payload.
 *
 * @param {unknown} rawItem Rich grid item payload.
 * @return {StreamVideo | null} Stream video payload or null.
 */
function normalizeStreamVideo(rawItem: unknown): StreamVideo | null {
  const richItem = asRecord(asRecord(rawItem)?.richItemRenderer);
  const content = asRecord(richItem?.content);
  const videoRenderer = asRecord(content?.videoRenderer);
  if (videoRenderer) {
    const videoId = flattenText(videoRenderer.videoId);
    const title = flattenText(videoRenderer.title);
    const relativeUrl = flattenText(
      getNested(
        videoRenderer,
        ["navigationEndpoint", "commandMetadata", "webCommandMetadata", "url"]
      )
    );
    if (!videoId || !title || !relativeUrl.startsWith("/watch")) {
      return null;
    }

    return {
      videoId,
      title,
      videoUrl: `https://www.youtube.com${relativeUrl}`,
      publishedText: flattenText(videoRenderer.publishedTimeText),
    };
  }

  const lockup = asRecord(content?.lockupViewModel);
  if (!lockup) {
    return null;
  }

  const videoId = flattenText(lockup.contentId);
  const title = flattenText(
    getNested(lockup, ["metadata", "lockupMetadataViewModel", "title"])
  );
  const relativeUrl = flattenText(
    getNested(
      lockup,
      [
        "rendererContext",
        "commandContext",
        "onTap",
        "innertubeCommand",
        "commandMetadata",
        "webCommandMetadata",
        "url",
      ]
    )
  );
  if (!videoId || !title || !relativeUrl.startsWith("/watch")) {
    return null;
  }

  const metadataRows = getNested(
    lockup,
    [
      "metadata",
      "lockupMetadataViewModel",
      "metadata",
      "contentMetadataViewModel",
      "metadataRows",
    ]
  );
  const metadataParts: string[] = [];
  if (Array.isArray(metadataRows)) {
    for (const row of metadataRows) {
      const parts = getNested(row, ["metadataParts"]);
      if (!Array.isArray(parts)) {
        continue;
      }
      for (const part of parts) {
        const text = flattenText(getNested(part, ["text"]));
        if (text) {
          metadataParts.push(text);
        }
      }
    }
  }

  const publishedText =
    metadataParts.find((part) => part.toLowerCase().includes("streamed")) ??
    metadataParts.join(" | ");

  return {
    videoId,
    title,
    videoUrl: `https://www.youtube.com${relativeUrl}`,
    publishedText,
  };
}

/**
 * Extract the recent stream videos shown on the channel page.
 *
 * @param {string} html Channel page HTML.
 * @param {number} limit Maximum number of videos to return.
 * @return {StreamVideo[]} Recent stream videos in page order.
 */
export function extractRecentStreamVideosFromHtml(
  html: string,
  limit?: number
): StreamVideo[] {
  if (limit !== undefined && (!Number.isInteger(limit) || limit <= 0)) {
    throw new Error("limit must be a positive integer.");
  }

  const initialData = extractInitialDataFromHtml(html);
  const streamsTab = findStreamsTab(initialData);
  const fallbackTab = findFallbackChannelTab(initialData);
  const contents =
    extractRichGridContents(streamsTab) ??
    extractRichGridContents(fallbackTab);
  if (!contents) {
    throw new Error(
      streamsTab && !fallbackTab ?
        "Streams tab is missing rich grid contents." :
        "Could not find a YouTube channel tab with recent videos."
    );
  }

  const videos: StreamVideo[] = [];
  for (const item of contents) {
    const video = normalizeStreamVideo(item);
    if (!video) {
      continue;
    }
    videos.push(video);
    if (limit !== undefined && videos.length >= limit) {
      break;
    }
  }

  if (videos.length === 0) {
    throw new Error("No stream videos were found on the channel page.");
  }

  return videos;
}

/**
 * Discover recent stream videos from a YouTube channel streams page.
 *
 * @param {string} channelUrl Channel streams URL.
 * @param {number} limit Maximum number of videos to return.
 * @param {RawTextFetcher} fetcher Override fetcher for tests.
 * @param {ExportFilters} filters Optional title filters.
 * @return {Promise<StreamVideo[]>} Recent stream videos.
 */
export async function discoverRecentStreamVideos(
  channelUrl: string,
  limit: number,
  fetcher: RawTextFetcher = fetchText,
  filters: ExportFilters = {}
): Promise<StreamVideo[]> {
  let lastError: unknown = null;
  for (let attempt = 1; attempt <= STREAM_DISCOVERY_ATTEMPTS; attempt++) {
    try {
      const html = await fetcher(channelUrl);
      const discovered = extractRecentStreamVideosFromHtml(html);
      const filtered = filterStreamVideos(discovered, filters);
      if (filtered.length === 0) {
        throw new Error(
          "No matching stream videos were found on the channel page."
        );
      }
      return filtered.slice(0, limit);
    } catch (error) {
      lastError = error;
      if (attempt < STREAM_DISCOVERY_ATTEMPTS) {
        await delay(attempt * 750);
      }
    }
  }

  if (lastError instanceof Error) {
    throw lastError;
  }
  throw new Error("Unable to discover recent stream videos.");
}

/**
 * Extract YouTube player response from watch page HTML.
 *
 * @param {string} watchHtml Raw watch page HTML.
 * @return {Record<string, unknown> | null} Parsed player response.
 */
function extractPlayerResponseFromWatchHtml(
  watchHtml: string
): Record<string, unknown> | null {
  const markers = [
    "ytInitialPlayerResponse = ",
    "var ytInitialPlayerResponse = ",
    "window['ytInitialPlayerResponse'] = ",
    "window[\"ytInitialPlayerResponse\"] = ",
  ];
  for (const marker of markers) {
    const parsed = extractJsonObjectAfterMarker(watchHtml, marker);
    const record = asRecord(parsed);
    if (record) {
      return record;
    }
  }
  return null;
}

/**
 * Parse the first valid date candidate.
 *
 * @param {unknown[]} values Candidate raw values.
 * @return {Date | null} Parsed date or null.
 */
function parseFirstValidDate(values: unknown[]): Date | null {
  for (const value of values) {
    if (typeof value !== "string") {
      continue;
    }
    const trimmed = value.trim();
    if (!trimmed) {
      continue;
    }
    const parsed = new Date(trimmed);
    if (!Number.isNaN(parsed.getTime())) {
      return parsed;
    }
  }
  return null;
}

/**
 * Infer a speaker name from a YouTube title when possible.
 *
 * @param {string} title Video title.
 * @return {string | null} Parsed speaker or null.
 */
export function inferSpeakerFromTitle(title: string): string | null {
  const cleaned = title.replace(/\s+/g, " ").trim();
  if (!cleaned) {
    return null;
  }

  const cleanCandidate = (candidate: string): string | null => {
    const normalized = candidate
      .replace(
        /^(?:khutbah|khutba|jummah|jumu'?ah)\s+by\s+/i,
        ""
      )
      .replace(/^by\s+/i, "")
      .trim();
    if (!normalized || /^\d/.test(normalized)) {
      return null;
    }
    return normalized;
  };

  const byMatch = cleaned.match(
    /(?:khutbah|khutba|jummah|jumu'?ah)[^|:-]*\bby\s+(.+)$/i
  );
  if (byMatch?.[1]) {
    return cleanCandidate(byMatch[1]);
  }

  const honorificPattern =
    /^(?:imam|shaykh(?:\s+dr\.?)?|sheikh|dr\.?|ustadh|mufti)\b/i;
  const segments = cleaned
    .split("|")
    .map((segment) => segment.trim())
    .filter((segment) => segment.length > 0);
  for (let i = segments.length - 1; i >= 0; i--) {
    if (honorificPattern.test(segments[i])) {
      return cleanCandidate(segments[i]);
    }
  }

  const dashMatch = cleaned.match(
    /[-–—]\s*((?:imam|shaykh(?:\s+dr\.?)?|sheikh|dr\.?|ustadh|mufti)\b.+)$/i
  );
  if (dashMatch?.[1]) {
    return cleanCandidate(dashMatch[1]);
  }

  return null;
}

/**
 * Extract publish date and speaker metadata from watch HTML.
 *
 * @param {string} watchHtml Raw watch page HTML.
 * @param {string} title Video title for speaker heuristics.
 * @return {WatchVideoMetadata} Parsed metadata.
 */
export function extractWatchVideoMetadataFromHtml(
  watchHtml: string,
  title: string
): WatchVideoMetadata {
  const playerResponse = extractPlayerResponseFromWatchHtml(watchHtml);
  const publishedAt = parseFirstValidDate([
    getNested(playerResponse, [
      "microformat",
      "playerMicroformatRenderer",
      "publishDate",
    ]),
    getNested(playerResponse, [
      "microformat",
      "playerMicroformatRenderer",
      "uploadDate",
    ]),
    watchHtml.match(/"publishDate":"([^"]+)"/)?.[1],
    watchHtml.match(/"uploadDate":"([^"]+)"/)?.[1],
    watchHtml.match(/itemprop="datePublished"\s+content="([^"]+)"/)?.[1],
    watchHtml.match(/itemprop="uploadDate"\s+content="([^"]+)"/)?.[1],
  ]);

  return {
    publishedAt,
    speaker: inferSpeakerFromTitle(title),
  };
}

/**
 * Fetch watch-page metadata for a video.
 *
 * @param {string} videoUrl Full YouTube watch URL.
 * @param {string} title Video title.
 * @param {RawTextFetcher} fetcher Raw text fetcher.
 * @return {Promise<WatchVideoMetadata>} Parsed metadata.
 */
export async function fetchWatchVideoMetadata(
  videoUrl: string,
  title: string,
  fetcher: RawTextFetcher = fetchText
): Promise<WatchVideoMetadata> {
  const watchHtml = await fetcher(videoUrl);
  return extractWatchVideoMetadataFromHtml(watchHtml, title);
}

/**
 * Normalize title text for loose keyword matching.
 *
 * @param {string} value Raw title or keyword text.
 * @return {string} Normalized text.
 */
function normalizeForKeywordMatch(value: string): string {
  return value
    .normalize("NFKD")
    .split("")
    .map((char) => stripNonAscii(char))
    .join("")
    .toLowerCase()
    .replace(/['`’]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

/**
 * Filter videos by optional title keywords.
 *
 * @param {StreamVideo[]} videos Candidate videos.
 * @param {ExportFilters} filters Export filters.
 * @return {StreamVideo[]} Filtered videos.
 */
export function filterStreamVideos(
  videos: StreamVideo[],
  filters: ExportFilters = {}
): StreamVideo[] {
  const titleKeywords = (filters.titleKeywords ?? [])
    .map((keyword) => normalizeForKeywordMatch(keyword))
    .filter((keyword) => keyword.length > 0);
  if (titleKeywords.length === 0) {
    return videos;
  }

  return videos.filter((video) => {
    const normalizedTitle = normalizeForKeywordMatch(video.title);
    return titleKeywords.some((keyword) => normalizedTitle.includes(keyword));
  });
}

/**
 * Normalize a raw caption track.
 *
 * @param {unknown} rawTrack Raw track payload.
 * @return {CaptionTrack | null} Normalized caption track.
 */
function normalizeCaptionTrack(rawTrack: unknown): CaptionTrack | null {
  const track = asRecord(rawTrack);
  if (!track) {
    return null;
  }

  const baseUrl = flattenText(track.baseUrl);
  const languageCode = flattenText(track.languageCode);
  if (!baseUrl || !languageCode) {
    return null;
  }

  const kind = flattenText(track.kind);
  const vssId = flattenText(track.vssId);
  return {
    baseUrl,
    languageCode,
    isAutoGenerated: kind === "asr" || vssId.startsWith("a."),
  };
}

/**
 * Read available caption tracks from a player response.
 *
 * @param {Record<string, unknown>} playerResponse Parsed player response.
 * @return {CaptionTrack[]} Caption tracks.
 */
function extractCaptionTracks(
  playerResponse: Record<string, unknown>
): CaptionTrack[] {
  const rawTracks = getNested(
    playerResponse,
    ["captions", "playerCaptionsTracklistRenderer", "captionTracks"]
  );
  if (!Array.isArray(rawTracks)) {
    return [];
  }

  return rawTracks
    .map((track) => normalizeCaptionTrack(track))
    .filter((track): track is CaptionTrack => track !== null);
}

/**
 * Choose the best caption track, preferring manual English captions.
 *
 * @param {CaptionTrack[]} tracks All available tracks.
 * @return {CaptionTrack | null} Selected track.
 */
function chooseCaptionTrack(tracks: CaptionTrack[]): CaptionTrack | null {
  if (tracks.length === 0) {
    return null;
  }

  const manualTracks = tracks.filter((track) => !track.isAutoGenerated);
  const pool = manualTracks.length > 0 ? manualTracks : tracks;
  const englishTrack = pool.find((track) =>
    track.languageCode === "en" || track.languageCode.startsWith("en-")
  );
  return englishTrack ?? pool[0];
}

/**
 * Decode common HTML entities.
 *
 * @param {string} input Raw text.
 * @return {string} Decoded text.
 */
function decodeHtmlEntities(input: string): string {
  const namedEntities: Record<string, string> = {
    amp: "&",
    lt: "<",
    gt: ">",
    quot: "\"",
    apos: "'",
    nbsp: " ",
  };

  let decoded = input;
  for (let pass = 0; pass < 3; pass++) {
    const next = decoded.replace(
      /&(#x[0-9a-fA-F]+|#\d+|[a-zA-Z]+);/g,
      (full, entity: string) => {
        if (entity.startsWith("#x") || entity.startsWith("#X")) {
          const codePoint = Number.parseInt(entity.slice(2), 16);
          return Number.isFinite(codePoint) ?
            String.fromCodePoint(codePoint) :
            full;
        }
        if (entity.startsWith("#")) {
          const codePoint = Number.parseInt(entity.slice(1), 10);
          return Number.isFinite(codePoint) ?
            String.fromCodePoint(codePoint) :
            full;
        }
        return namedEntities[entity] ?? full;
      }
    );
    if (next === decoded) {
      break;
    }
    decoded = next;
  }

  return decoded;
}

/**
 * Normalize a caption fragment into plain text.
 *
 * @param {string} value Raw caption fragment.
 * @return {string} Normalized caption fragment.
 */
export function normalizeCaptionFragment(value: string): string {
  const decoded = decodeHtmlEntities(value);
  const withoutTags = decoded.replace(/<[^>]*>/g, " ");
  return withoutTags.replace(/\s+/g, " ").trim();
}

/**
 * Join caption lines while removing immediate duplicates.
 *
 * @param {string[]} lines Caption lines.
 * @return {string} Joined transcript.
 */
function dedupeAndJoinCaptionLines(lines: string[]): string {
  const deduped: string[] = [];
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) {
      continue;
    }
    if (deduped[deduped.length - 1] === line) {
      continue;
    }
    deduped.push(line);
  }
  return deduped.join("\n").trim();
}

/**
 * Parse YouTube json3 captions into transcript text.
 *
 * @param {string} payload Caption payload.
 * @return {string} Parsed transcript text.
 */
function parseJson3Captions(payload: string): string {
  try {
    const parsed = JSON.parse(payload) as Record<string, unknown>;
    const events = parsed.events;
    if (!Array.isArray(events)) {
      return "";
    }

    const lines: string[] = [];
    for (const event of events) {
      const eventRecord = asRecord(event);
      const segs = eventRecord?.segs;
      if (!Array.isArray(segs)) {
        continue;
      }

      const text = segs
        .map((seg) => {
          const segRecord = asRecord(seg);
          return segRecord && typeof segRecord.utf8 === "string" ?
            segRecord.utf8 :
            "";
        })
        .join("");
      const normalized = normalizeCaptionFragment(text);
      if (normalized) {
        lines.push(normalized);
      }
    }

    return dedupeAndJoinCaptionLines(lines);
  } catch {
    return "";
  }
}

/**
 * Parse YouTube XML captions into transcript text.
 *
 * @param {string} payload Caption payload.
 * @return {string} Parsed transcript text.
 */
function parseXmlCaptions(payload: string): string {
  const lines: string[] = [];
  const textRegex = /<text[^>]*>([\s\S]*?)<\/text>/g;
  let match = textRegex.exec(payload);
  while (match) {
    const normalized = normalizeCaptionFragment(match[1] ?? "");
    if (normalized) {
      lines.push(normalized);
    }
    match = textRegex.exec(payload);
  }
  return dedupeAndJoinCaptionLines(lines);
}

/**
 * Convert transcript segments into normalized transcript text.
 *
 * @param {Array<{text: string}>} segments Transcript segments.
 * @return {string} Transcript text.
 */
function normalizeTranscriptSegments(
  segments: Array<{text: string}>
): string {
  const lines = segments
    .map((segment) => normalizeCaptionFragment(segment.text))
    .filter((line) => line.length > 0);
  return dedupeAndJoinCaptionLines(lines);
}

/**
 * Fetch transcript by scraping the watch page caption tracks.
 *
 * @param {string} videoId YouTube video ID.
 * @param {RawTextFetcher} fetcher Raw text fetcher.
 * @return {Promise<TranscriptResult | null>} Transcript result.
 */
async function fetchTranscriptFromWatchPage(
  videoId: string,
  fetcher: RawTextFetcher = fetchText
): Promise<TranscriptResult | null> {
  const watchHtml = await fetcher(
    `https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}`
  );
  const playerResponse = extractPlayerResponseFromWatchHtml(watchHtml);
  if (!playerResponse) {
    return null;
  }

  const track = chooseCaptionTrack(extractCaptionTracks(playerResponse));
  if (!track) {
    return null;
  }

  const captionUrl = new URL(track.baseUrl);
  if (!captionUrl.searchParams.has("fmt")) {
    captionUrl.searchParams.set("fmt", "json3");
  }

  let payload = await fetcher(captionUrl.toString());
  let transcriptText = parseJson3Captions(payload);
  if (!transcriptText) {
    transcriptText = parseXmlCaptions(payload);
  }

  if (!transcriptText) {
    captionUrl.searchParams.delete("fmt");
    payload = await fetcher(captionUrl.toString());
    transcriptText = parseXmlCaptions(payload);
  }

  if (!transcriptText) {
    return null;
  }

  return {
    text: transcriptText,
    source: track.isAutoGenerated ?
      "youtube_watch_page_auto" :
      "youtube_watch_page",
    languageCode: track.languageCode,
    isAutoGenerated: track.isAutoGenerated,
  };
}

/**
 * Fetch transcript using the youtube-transcript-plus package.
 *
 * @param {string} videoId YouTube video ID.
 * @return {Promise<TranscriptResult | null>} Transcript result.
 */
async function fetchTranscriptFromTranscriptPlus(
  videoId: string
): Promise<TranscriptResult | null> {
  const response = await fetchTranscriptPlus(videoId);
  const transcriptText = normalizeTranscriptSegments(response.segments);
  if (!transcriptText) {
    return null;
  }

  const firstSegment = response.segments[0] ?? null;
  return {
    text: transcriptText,
    source: "youtube_transcript_plus",
    languageCode: firstSegment?.lang ?? null,
    isAutoGenerated: null,
  };
}

/**
 * Fetch transcript using the youtube-transcript package.
 *
 * @param {string} videoId YouTube video ID.
 * @return {Promise<TranscriptResult | null>} Transcript result.
 */
async function fetchTranscriptFromTranscriptApi(
  videoId: string
): Promise<TranscriptResult | null> {
  const segments = await YoutubeTranscriptApi.fetchTranscript(videoId);
  const transcriptText = normalizeTranscriptSegments(segments);
  if (!transcriptText) {
    return null;
  }

  return {
    text: transcriptText,
    source: "youtube_transcript",
    languageCode: null,
    isAutoGenerated: null,
  };
}

/**
 * Fetch the best available transcript for a video.
 *
 * @param {string} videoId YouTube video ID.
 * @param {RawTextFetcher} fetcher Raw text fetcher for watch-page scraping.
 * @return {Promise<TranscriptResult | null>} Transcript result.
 */
export async function fetchBestTranscriptForVideo(
  videoId: string,
  fetcher: RawTextFetcher = fetchText
): Promise<TranscriptResult | null> {
  const attempts: Array<() => Promise<TranscriptResult | null>> = [
    () => fetchTranscriptFromWatchPage(videoId, fetcher),
    () => fetchTranscriptFromTranscriptPlus(videoId),
    () => fetchTranscriptFromTranscriptApi(videoId),
  ];

  for (const attempt of attempts) {
    try {
      const transcript = await attempt();
      if (transcript?.text) {
        return transcript;
      }
    } catch {
      continue;
    }
  }

  return null;
}

/**
 * Convert a title into a stable file slug.
 *
 * @param {string} title Video title.
 * @return {string} File-safe slug.
 */
export function slugifyTitle(title: string): string {
  const normalized = title
    .normalize("NFKD")
    .split("")
    .map((char) => stripNonAscii(char))
    .join("")
    .toLowerCase();
  const slug = normalized
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
  return slug || "video";
}

/**
 * Build a stable folder slug from a channel URL.
 *
 * @param {string} channelUrl Channel URL.
 * @return {string} Channel folder slug.
 */
export function slugifyChannelUrl(channelUrl: string): string {
  try {
    const parsed = new URL(channelUrl);
    const segments = parsed.pathname.split("/").filter(Boolean);
    const handle = segments[0] ?? parsed.hostname;
    return slugifyTitle(handle.replace(/^@/, ""));
  } catch {
    return slugifyTitle(channelUrl);
  }
}

/**
 * Format a local date string for file naming.
 *
 * @param {Date} date Input date.
 * @return {string} YYYY-MM-DD in local time.
 */
function formatLocalDate(date: Date): string {
  const year = String(date.getFullYear());
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

/**
 * Build transcript document contents.
 *
 * @param {StreamVideo} video Stream video metadata.
 * @param {TranscriptResult} transcript Transcript payload.
 * @param {string} channelUrl Source channel page URL.
 * @param {Date} fetchedAt Fetch timestamp.
 * @param {TranscriptDocumentOptions} options Optional transcript metadata.
 * @return {string} File contents.
 */
export function buildTranscriptDocument(
  video: StreamVideo,
  transcript: TranscriptResult,
  channelUrl: string,
  fetchedAt: Date,
  options: TranscriptDocumentOptions = {}
): string {
  const headerLines = [
    `Title: ${video.title}`,
    `Video URL: ${video.videoUrl}`,
    `Source Page: ${channelUrl}`,
    `Published: ${video.publishedText || "Unknown"}`,
    `Fetched At: ${fetchedAt.toISOString()}`,
    `Transcript Source: ${transcript.source}`,
  ];
  if (options.metadata?.publishedAt) {
    headerLines.push(
      `Published At: ${options.metadata.publishedAt.toISOString()}`
    );
  }
  if (transcript.languageCode) {
    headerLines.push(`Language Code: ${transcript.languageCode}`);
  }
  if (transcript.isAutoGenerated !== null) {
    headerLines.push(
      `Auto Generated: ${transcript.isAutoGenerated ? "yes" : "no"}`
    );
  }
  if (options.metadata?.speaker) {
    headerLines.push(`Speaker: ${options.metadata.speaker}`);
  }

  return `${headerLines.join("\n")}\n\n${transcript.text.trim()}\n`;
}

/**
 * Parse a transcript export file into metadata and transcript text.
 *
 * @param {string} value Full transcript file contents.
 * @return {ParsedTranscriptDocument} Parsed transcript document.
 */
export function parseTranscriptDocument(
  value: string
): ParsedTranscriptDocument {
  const separator = value.indexOf("\n\n");
  const headerText = separator >= 0 ? value.slice(0, separator) : value;
  const transcriptText = (separator >= 0 ? value.slice(separator + 2) : "")
    .trim();
  const headerMap = new Map<string, string>();
  for (const line of headerText.split(/\r?\n/)) {
    const separatorIndex = line.indexOf(":");
    if (separatorIndex <= 0) {
      continue;
    }
    const key = line.slice(0, separatorIndex).trim().toLowerCase();
    const headerValue = line.slice(separatorIndex + 1).trim();
    if (key) {
      headerMap.set(key, headerValue);
    }
  }

  const fetchedAtRaw = headerMap.get("fetched at") ?? "";
  const publishedAtRaw = headerMap.get("published at") ?? "";
  const autoGeneratedRaw = headerMap.get("auto generated") ?? "";
  return {
    metadata: {
      title: headerMap.get("title") ?? "",
      videoUrl: headerMap.get("video url") ?? "",
      sourcePage: headerMap.get("source page") ?? "",
      publishedText: headerMap.get("published") ?? "",
      publishedAt: publishedAtRaw ? new Date(publishedAtRaw) : null,
      fetchedAt: fetchedAtRaw ? new Date(fetchedAtRaw) : null,
      transcriptSource: headerMap.get("transcript source") ?? "",
      languageCode: headerMap.get("language code") ?? null,
      isAutoGenerated: autoGeneratedRaw === "yes" ?
        true :
        autoGeneratedRaw === "no" ?
          false :
          null,
      speaker: headerMap.get("speaker") ?? null,
    },
    transcriptText,
  };
}

/**
 * Write a transcript export file.
 *
 * @param {string} outputDir Destination directory.
 * @param {StreamVideo} video Stream video metadata.
 * @param {TranscriptResult} transcript Transcript payload.
 * @param {string} channelUrl Source channel page URL.
 * @param {Date} fetchedAt Fetch timestamp.
 * @param {TranscriptDocumentOptions} options Optional transcript metadata.
 * @return {Promise<string>} Written file path.
 */
export async function writeTranscriptFile(
  outputDir: string,
  video: StreamVideo,
  transcript: TranscriptResult,
  channelUrl: string,
  fetchedAt: Date,
  options: TranscriptDocumentOptions = {}
): Promise<string> {
  await mkdir(outputDir, {recursive: true});
  const filename = `${formatLocalDate(fetchedAt)}__${video.videoId}__` +
    `${slugifyTitle(video.title)}.txt`;
  const filePath = path.join(outputDir, filename);
  const body = buildTranscriptDocument(
    video,
    transcript,
    channelUrl,
    fetchedAt,
    options
  );
  await writeFile(filePath, body, "utf8");
  return filePath;
}

/**
 * Run the full stream transcript export flow.
 *
 * @param {Object} options Export options.
 * @return {Promise<ExportRunResult>} Export result summary.
 */
export async function exportRecentStreamTranscripts(options: {
  channelUrl: string;
  limit: number;
  outputDir: string;
  mode: ExportMode;
  titleKeywords?: string[];
}): Promise<ExportRunResult> {
  const videos = await discoverRecentStreamVideos(
    options.channelUrl,
    options.limit,
    fetchText,
    {titleKeywords: options.titleKeywords}
  );
  const fetchedAt = new Date();
  const saved: SavedTranscriptFile[] = [];
  const skipped: SkippedTranscriptVideo[] = [];

  for (const video of videos) {
    const transcript = await fetchBestTranscriptForVideo(video.videoId);
    if (!transcript?.text) {
      skipped.push({
        video,
        reason: "Transcript unavailable from YouTube.",
      });
      continue;
    }

    let metadata: WatchVideoMetadata = {
      publishedAt: null,
      speaker: null,
    };
    try {
      metadata = await fetchWatchVideoMetadata(video.videoUrl, video.title);
    } catch {
      metadata = {
        publishedAt: null,
        speaker: null,
      };
    }

    const filePath = await writeTranscriptFile(
      options.outputDir,
      video,
      transcript,
      options.channelUrl,
      fetchedAt,
      {metadata}
    );
    saved.push({video, filePath, transcript, metadata});
  }

  return {
    channelUrl: options.channelUrl,
    mode: options.mode,
    limit: options.limit,
    titleKeywords: options.titleKeywords ?? [],
    errorMessage: null,
    saved,
    skipped,
  };
}

/**
 * Resolve the output directory for a channel in a multi-channel export.
 *
 * @param {string} baseOutputDir Base output directory.
 * @param {string} channelUrl Channel URL.
 * @param {number} channelCount Total number of requested channels.
 * @param {boolean} useChannelSubdirectories Force per-channel folders.
 * @return {string} Output directory for the channel.
 */
export function resolveChannelOutputDir(
  baseOutputDir: string,
  channelUrl: string,
  channelCount: number,
  useChannelSubdirectories = false
): string {
  return useChannelSubdirectories || channelCount > 1 ?
    path.join(baseOutputDir, slugifyChannelUrl(channelUrl)) :
    baseOutputDir;
}

/**
 * Run the export flow for multiple channel URLs.
 *
 * @param {Object} options Export options.
 * @return {Promise<MultiChannelExportResult>} Export result summary.
 */
export async function exportRecentStreamTranscriptsForChannels(options: {
  channelUrls: string[];
  limit: number;
  outputDir: string;
  mode: ExportMode;
  titleKeywords?: string[];
  useChannelSubdirectories?: boolean;
}): Promise<MultiChannelExportResult> {
  const results: ExportRunResult[] = [];
  for (const channelUrl of options.channelUrls) {
    const channelOutputDir = resolveChannelOutputDir(
      options.outputDir,
      channelUrl,
      options.channelUrls.length,
      options.useChannelSubdirectories
    );
    try {
      const result = await exportRecentStreamTranscripts({
        channelUrl,
        limit: options.limit,
        outputDir: channelOutputDir,
        mode: options.mode,
        titleKeywords: options.titleKeywords,
      });
      results.push(result);
    } catch (error) {
      results.push({
        channelUrl,
        mode: options.mode,
        limit: options.limit,
        titleKeywords: options.titleKeywords ?? [],
        errorMessage: error instanceof Error ? error.message : String(error),
        saved: [],
        skipped: [],
      });
    }
  }

  return {
    mode: options.mode,
    limit: options.limit,
    titleKeywords: options.titleKeywords ?? [],
    results,
  };
}

/**
 * Build a concise stdout summary for the export run.
 *
 * @param {ExportRunResult} result Export result.
 * @return {string} Human-readable run summary.
 */
export function formatRunSummary(result: ExportRunResult): string {
  const lines = [
    `Mode: ${result.mode}`,
    `Channel: ${result.channelUrl}`,
    `Requested: ${result.limit}`,
    `Title keywords: ${
      result.titleKeywords.length > 0 ?
        result.titleKeywords.join(", ") :
        "none"
    }`,
    `Saved: ${result.saved.length}`,
    `Skipped: ${result.skipped.length}`,
  ];
  if (result.errorMessage) {
    lines.push(`Error: ${result.errorMessage}`);
  }

  if (result.saved.length > 0) {
    lines.push("");
    lines.push("Saved files:");
    for (const item of result.saved) {
      lines.push(
        `- ${item.video.title} -> ${item.filePath} ` +
        `(${item.transcript.source})`
      );
    }
  }

  if (result.skipped.length > 0) {
    lines.push("");
    lines.push("Skipped videos:");
    for (const item of result.skipped) {
      lines.push(`- ${item.video.title} (${item.reason})`);
    }
  }

  return `${lines.join("\n")}\n`;
}

/**
 * Build a concise stdout summary for multiple channel runs.
 *
 * @param {MultiChannelExportResult} result Multi-channel result.
 * @return {string} Human-readable run summary.
 */
export function formatMultiChannelRunSummary(
  result: MultiChannelExportResult
): string {
  const totalSaved = result.results.reduce(
    (sum, item) => sum + item.saved.length,
    0
  );
  const totalSkipped = result.results.reduce(
    (sum, item) => sum + item.skipped.length,
    0
  );
  const lines = [
    `Mode: ${result.mode}`,
    `Channels: ${result.results.length}`,
    `Requested per channel: ${result.limit}`,
    `Title keywords: ${
      result.titleKeywords.length > 0 ?
        result.titleKeywords.join(", ") :
        "none"
    }`,
    `Saved total: ${totalSaved}`,
    `Skipped total: ${totalSkipped}`,
  ];

  for (const channelResult of result.results) {
    lines.push("");
    lines.push(`Channel: ${channelResult.channelUrl}`);
    lines.push(`Saved: ${channelResult.saved.length}`);
    lines.push(`Skipped: ${channelResult.skipped.length}`);
    if (channelResult.errorMessage) {
      lines.push(`Error: ${channelResult.errorMessage}`);
    }
    if (channelResult.saved.length > 0) {
      for (const item of channelResult.saved) {
        lines.push(
          `- ${item.video.title} -> ${item.filePath} ` +
          `(${item.transcript.source})`
        );
      }
    }
    if (channelResult.skipped.length > 0) {
      for (const item of channelResult.skipped) {
        lines.push(`- ${item.video.title} (${item.reason})`);
      }
    }
  }

  return `${lines.join("\n")}\n`;
}
